### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sup** [marblesoda/marble#1]
roadmap for 0.1.0 (first beta release):

- [ ] basic rails app
- [ ] initial design
- [ ] user system
- [ ] status updates (= tweeting)
- [ ] initial version of a timeline
- [ ] basic user profiles

we can go further from there
